/**
 * Staff Service Reports - JavaScript functionality
 * Handles DataTable initialization, Chart.js, and export functionality for staff reports
 */

function initializeStaffReports(reportData) {
    if (!reportData || !reportData.hasData) {
        console.log('No staff report data available for initialization');
        return;
    }
    
    console.log('Initializing staff reports with data:', reportData);
    
    var cityLogo = document.getElementById('cityLogo').src;
    var serviceLogoElement = document.getElementById('serviceLogo');
    var serviceLogo = '';
    
    // Handle service logo
    if (serviceLogoElement) {
        serviceLogo = serviceLogoElement.src;
    }
    
    // PDF export customization for staff
    var pdfCustomization = function(doc) {
        doc.content.unshift({
            columns: [
                { image: cityLogo, width: 80, alignment: 'center' },
                { 
                    text: [
                        { text: 'My Service Feedback Report\n', fontSize: 16, bold: true, alignment: 'center' },
                        { text: 'Service: ' + reportData.serviceName + '\n', fontSize: 12, alignment: 'center' },
                        { text: 'Period: ' + reportData.yearMonth, fontSize: 12, alignment: 'center' }
                    ],
                    alignment: 'center',
                    margin: [0, 10, 0, 20]
                },
                serviceLogo ? { image: serviceLogo, width: 80, alignment: 'center' } : { text: 'No Image', alignment: 'center', width: 80 }
            ],
            columnGap: 10,
            margin: [0, 0, 0, 20]
        });
        
        // Add footer with staff name
        doc['footer'] = function(currentPage, pageCount) {
            return {
                columns: [
                    { 
                        text: 'Generated by: ' + reportData.staffName, 
                        alignment: 'left',
                        margin: [20, 0, 0, 0],
                        fontSize: 10
                    },
                    { 
                        text: 'Page ' + currentPage.toString() + ' of ' + pageCount, 
                        alignment: 'right',
                        margin: [0, 0, 20, 0],
                        fontSize: 10
                    }
                ],
                margin: [20, 10]
            };
        };
    };

    // Initialize DataTable with export buttons for staff
    $('#reportTable').DataTable({
        dom: 'Bfrtip',
        pageLength: 10,
        responsive: true,
        buttons: [
            {
                extend: 'copy',
                title: 'My Service Feedback Report',
                messageTop: 'Service: ' + reportData.serviceName + '\nPeriod: ' + reportData.yearMonth,
                messageBottom: 'Generated by: ' + reportData.staffName,
                className: 'btn-sm'
            },
            {
                extend: 'csv',
                title: 'My Service Feedback Report',
                messageTop: 'Service: ' + reportData.serviceName + '\nPeriod: ' + reportData.yearMonth,
                messageBottom: 'Generated by: ' + reportData.staffName,
                className: 'btn-sm'
            },
            {
                extend: 'excel',
                title: 'My Service Feedback Report',
                messageTop: 'Service: ' + reportData.serviceName + '\nPeriod: ' + reportData.yearMonth,
                messageBottom: 'Generated by: ' + reportData.staffName,
                className: 'btn-sm'
            },
            {
                extend: 'pdf',
                title: '',
                messageTop: '',
                className: 'btn-sm',
                customize: pdfCustomization
            },
            {
                extend: 'print',
                title: '',
                messageTop: function() {
                    var html = '<div style="width:100%;display:flex;justify-content:center;align-items:center;gap:40px;margin-bottom:10px;">' +
                        '<img src="' + cityLogo + '" style="height:80px;">' +
                        '<span style="font-size:16px;font-weight:bold;margin:0 15px;">My Service Feedback Report</span>' +
                        (serviceLogo ? 
                            '<img src="' + serviceLogo + '" style="height:80px;">' : 
                            '<div style="height:80px;width:80px;background:#f8f9fa;border:2px dashed #dee2e6;display:flex;align-items:center;justify-content:center;color:#6c757d;flex-direction:column;font-size:10px;"><i class="fas fa-image" style="font-size:18px;margin-bottom:2px;"></i>No Image</div>'
                        ) +
                        '</div>';
                    html += '<div style="text-align:center;margin-bottom:8px;font-size:12px;">Service: ' + reportData.serviceName + '<br>Period: ' + reportData.yearMonth + '</div>';
                    html += '<div style="text-align:left;margin-bottom:8px;font-size:12px;">Generated by: ' + reportData.staffName + '</div>';
                    html += '<hr style="border:1px solid #000;margin:10px 0;">';
                    return html;
                },
                customize: function (win) {
                    // Remove extra styling and ensure single page
                    $(win.document.body)
                        .css('margin', '5mm')
                        .css('padding', '0')
                        .find('table')
                        .css('font-size', '9pt')
                        .css('width', '100%');
                    
                    // Remove any empty space at the end
                    $(win.document.body).find('div:empty').remove();
                    
                    // Add footer for print
                    $(win.document.body).append(
                        '<div style="position:fixed;bottom:20px;left:20px;font-size:12px;">Generated by: ' + reportData.staffName + '</div>'
                    );
                    
                    return win;
                }
            },
            'colvis'
        ]
    });

    // Initialize Chart.js for service sentiment (Pie Chart)
    const ctxPie = document.getElementById('servicePieChart');
    if (ctxPie) {
        const pieChart = new Chart(ctxPie, {
            type: 'pie',
            data: {
                labels: ['Positive', 'Negative', 'Neutral'],
                datasets: [{
                    data: reportData.totals,
                    backgroundColor: [
                        'rgba(40, 167, 69, 0.8)',
                        'rgba(220, 53, 69, 0.8)',
                        'rgba(255, 193, 7, 0.8)'
                    ],
                    borderColor: [
                        'rgba(40, 167, 69, 1)',
                        'rgba(220, 53, 69, 1)',
                        'rgba(255, 193, 7, 1)'
                    ],
                    borderWidth: 2
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { 
                        position: 'bottom',
                        labels: {
                            padding: 20,
                            usePointStyle: true,
                            font: {
                                size: window.innerWidth < 768 ? 10 : 12
                            }
                        }
                    },
                    title: {
                        display: true,
                        text: 'Sentiment Distribution',
                        font: {
                            size: window.innerWidth < 768 ? 14 : 16,
                            weight: 'bold'
                        }
                    }
                }
            }
        });
        
        // Adjust chart on window resize
        $(window).on('resize', function() {
            pieChart.update();
        });
    } else {
        console.warn('Chart canvas element not found');
    }
}

// Initialize when document is ready
$(document).ready(function() {
    // Enable sidebar toggle for mobile
    $('[data-widget="pushmenu"]').on('click', function() {
        $('body').toggleClass('sidebar-open');
    });
    
    // Close sidebar when clicking overlay
    $('.sidebar-overlay').on('click', function() {
        $('body').removeClass('sidebar-open');
    });

    // Check if staff report data is available
    if (typeof window.staffReportData !== 'undefined') {
        console.log('Staff report data found, initializing reports...');
        initializeStaffReports(window.staffReportData);
    } else {
        console.log('No staff report data available');
    }
});